using System.Diagnostics.CodeAnalysis;

namespace FeatureSwitchDemo;

public class MyFeature
{
    [FeatureSwitchDefinition("Feature.IsSupported")]
    public static bool IsSupported => AppContext.TryGetSwitch("Feature.IsSupported", out bool isEnabled) ? isEnabled : true;

    public static void Implementation() => Console.WriteLine("" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!" +
        "Hello, Implementation!"
        );

}
